module.exports = {
  "count":50100,
  "results":[
    {
      "listing_id":205149514,
      "state":"active",
      "user_id":37476441,
      "category_id":69151567,
      "title":"FLASH SALE 20% OFF Gold Name Necklace  \/ Personalized Gold Name Necklace \/ Personalized 14K Gold Filled Name Necklace \/ Valentine&#39;s Day Gift",
      "description":"Gold Name Necklace  \/ Personalized Gold Name Necklace \/ 14K Gold Filled Name Necklace \/ Choose any name to personalize \/ Christmas Gift\n\n\n\n%100 Handmad for your size in my Atelier\nThis bar necklace is 925 Sterling Silver and 14K Gold Filled \n\n\n                                                         \u22ef\u22ef HOW - TO - ORDER \u22ef\u22ef\n\n\n\u2665 Just let us know in the &#39;NOTES&#39; section upon ordering as to what NAME you&#39;d like on the charm and FONT NUMBER. \n\n(Any font is available, not just our featured fonts)\n\n\u2665 Brooklyn necklace is my special font . If a font is not given, you will receive the font that is pictured. \n\n                    \u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\u22ef\n\n\u2665 The item will come with a gift box, ready to be gifted. \n\n\u2665 Multiples are available also for bridal parties, or as bridesmaids gift sets (don&#39;t forget to ask about special discounts before ordering). \n\n\u2665Special offer for Multiple Orders (more than 5 items) \u2665 Contact us for coupon code discount \u2665\n\n\u2665 Please read shipping & policies section for additional shipping information, return-exchange policy, and more.\n\n+++++++++++++++++++++++++++++++++\n\nDELIVERY:\nAll items purchased will be shipped within 3-5 business days via Turkish Mail Service with a tracking number. If you wish to upgrade your shipping feel free to contact me.\nPlease see my policies section for shipping and return information\n\n+++++++++++++++++++++++++++++++++\nWhat is 14k Gold Fill ?\nGold filled components contain 100+ times more real gold than gold plated components and are very durable and tarnish resistant. Gold filled jewelry is a beautiful, affordable alternative to solid gold, and can be worn by people with sensitive skin.\n\n+++++++++++++++++++++++++++++++++\n\nENTER MY SHOP HERE:\nhttp:\/\/lhappywayjewelry.etsy.com\n\n+++++++++++++++++++++++++++++++++\n\nEXPRESS SH\u0130PP\u0130NG\nIf you wish to upgrade your shipping you can buy it \nhttps:\/\/www.etsy.com\/listing\/183335887\/fedex-express-worldwide-shipping?ref=shop_home_active_21\n\n....................................................\nINSTAGRAM:\nFollow us on Instagram for pictures and items not seen anywhere else!\n@happywayjewelry\n\n\n....................................................\nFACEBOOK:\nMake sure you &quot;LIKE&quot; our facebook page to receive coupons and special offers!\nhttps:\/\/www.facebook.com\/HappyWayJewelry\n\n\n....................................................\nPINTEREST:\nhttps:\/\/www.pinterest.com\/Happywayjewelry\/\n\n\n\n\u2665Thank you for your interest. \u2665\n\u2665Please check out our other items and be sure to add us to your favorites\u2665",
      "creation_tsz":1455618410,
      "ending_tsz":1466069210,
      "original_creation_tsz":1411919643,
      "last_modified_tsz":1455618410,
      "price":"36.00",
      "currency_code":"USD",
      "quantity":42,
      "tags":[
        "name necklace",
        "necklace",
        "jewelry",
        "bridesmaids gift",
        "name jewelry",
        "personal necklace",
        "single name necklace",
        "personalized jewelry",
        "name necklace gold",
        "gold name necklace",
        "personalized",
        "tiny name necklace",
        "custom name necklace"
      ],
      "category_path":[
        "Jewelry",
        "Necklace"
      ],
      "category_path_ids":[
        68887482,
        69151567
      ],
      "materials":[
        "925 sterling silver",
        "14K Gold Fill"
      ],
      "shop_section_id":18138486,
      "featured_rank":12,
      "state_tsz":1455311659,
      "url":"https:\/\/www.etsy.com\/listing\/205149514\/flash-sale-20-off-gold-name-necklace?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":38477,
      "num_favorers":3592,
      "shipping_template_id":2142752301,
      "processing_min":3,
      "processing_max":5,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"made_to_order",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":"women",
      "occasion":"wedding",
      "style":[
        "Minimalist",
        "High Fashion"
      ],
      "non_taxable":false,
      "is_customizable":true,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":true,
      "taxonomy_id":1227,
      "taxonomy_path":[
        "Jewelry",
        "Necklaces",
        "Monogram & Name Necklaces"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":220141055,
      "state":"active",
      "user_id":37476441,
      "category_id":69151567,
      "title":"Gold Sideways Cross Necklace\/ Sterling Silver Cross Necklace \/ 14K Gold Filled Mini  necklace \/  Mother&#39;s Day Gifts \/ Valentine&#39;s Day Gift",
      "description":"Gold Sideways Cross Necklace\/ Sterling Silver Cross Necklace \/ 14K Gold Filled Mini Cross necklace \/  Mother&#39;s Day Gifts \/ Graduation Gift\n\nThis delicate gold sideways cross necklace is made out of 14 kt gold filled material, the cross charm (aprox. 10 mm) is gold plated. It is a minimalist small cross  charm which gives the final touch to your style. It can be worn everyday or for special occasions. The necklace is very elegant and stylish.\n\nAvailable options: \n14k white gold filled over sterling silver\n14k yellow gold filled over sterling silver\n14k rose gold filled over sterling silver \n\n\n\u2665 Please read shipping & policies section for additional shipping information, return-exchange policy, and more.\n\n+++++++++++++++++++++++++++++++++\n\nDELIVERY:\nAll items purchased will be shipped within 3-5 business days via Turkish Mail Service with a tracking number. If you wish to upgrade your shipping feel free to contact me.\nPlease see my policies section for shipping and return information\n\n+++++++++++++++++++++++++++++++++\nWhat is 14k Gold Fill ?\nGold filled components contain 100+ times more real gold than gold plated components and are very durable and tarnish resistant. Gold filled jewelry is a beautiful, affordable alternative to solid gold, and can be worn by people with sensitive skin.\n\n+++++++++++++++++++++++++++++++++\n\nENTER MY SHOP HERE:\nhttp:\/\/happywayjewelry.etsy.com\n\n+++++++++++++++++++++++++++++++++\n\nEXPRESS SH\u0130PP\u0130NG\nIf you wish to upgrade your shipping you can buy it \nhttps:\/\/www.etsy.com\/listing\/183335887\/fedex-express-worldwide-shipping?ref=shop_home_active_21\n\n\n\u2665Thank you for your interest. \u2665\n\u2665Please check out our other items and be sure to add us to your favorites\u2665",
      "creation_tsz":1455618410,
      "ending_tsz":1466069210,
      "original_creation_tsz":1422311253,
      "last_modified_tsz":1455618410,
      "price":"35.00",
      "currency_code":"USD",
      "quantity":86,
      "tags":[
        "bridesmaid gift",
        "Jewelry",
        "Necklace",
        "Bridesmaid",
        "sideway necklace",
        "elegant necklace",
        "everyday necklace",
        "cross necklace",
        "small cross necklace",
        "sideways cross",
        "sideway cross",
        "gold cross",
        "Valentine's Day Gift"
      ],
      "category_path":[
        "Jewelry",
        "Necklace"
      ],
      "category_path_ids":[
        68887482,
        69151567
      ],
      "materials":[
        "sterling silver",
        "14k Gold Filled"
      ],
      "shop_section_id":16092873,
      "featured_rank":null,
      "state_tsz":1437145672,
      "url":"https:\/\/www.etsy.com\/listing\/220141055\/gold-sideways-cross-necklace-sterling?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":2521,
      "num_favorers":326,
      "shipping_template_id":2142752301,
      "processing_min":3,
      "processing_max":5,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"made_to_order",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":"women",
      "occasion":"birthday",
      "style":[
        "High Fashion",
        "Minimalist"
      ],
      "non_taxable":false,
      "is_customizable":true,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":true,
      "taxonomy_id":1217,
      "taxonomy_path":[
        "Jewelry",
        "Necklaces"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":206528316,
      "state":"active",
      "user_id":42728757,
      "category_id":68892008,
      "title":"Ostrich Easter Egg decorated with Wax Traditional Slavic Technique, Kraslice, Pysanka",
      "description":"Ostrich Easter Egg decorated with Wax Traditional Slavic Technique, Kraslice, Pysanka, \n\nHand painted Natural color Ostrich egg.\nThis egg is decorated with wax.\nThe eggs are decorated using a wax pinhead and is the oldest and most widely used technique. The tradition of painted eggs back to the depths of the Slavic culture.\n\nFor more information write to me\nI look forward to your questions",
      "creation_tsz":1455618407,
      "ending_tsz":1466069207,
      "original_creation_tsz":1412877438,
      "last_modified_tsz":1455618407,
      "price":"90.00",
      "currency_code":"USD",
      "quantity":1,
      "tags":[
        "easter",
        "egg",
        "wax",
        "decoration",
        "eggs",
        "easter eggs",
        "polish",
        "ukrainian",
        "slavic",
        "kraslice",
        "pysanky",
        "blown",
        "ostrich"
      ],
      "category_path":[
        "Housewares",
        "Home Decor"
      ],
      "category_path_ids":[
        69150425,
        68892008
      ],
      "materials":[
        "egg",
        "wax",
        "color",
        "painted"
      ],
      "shop_section_id":16050786,
      "featured_rank":null,
      "state_tsz":1455571845,
      "url":"https:\/\/www.etsy.com\/listing\/206528316\/ostrich-easter-egg-decorated-with-wax?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":1245,
      "num_favorers":136,
      "shipping_template_id":1640282338,
      "processing_min":3,
      "processing_max":5,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":"easter",
      "style":null,
      "non_taxable":false,
      "is_customizable":true,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":1002,
      "taxonomy_path":[
        "Home & Living",
        "Home D\u00e9cor"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":212387093,
      "state":"active",
      "user_id":23046269,
      "category_id":69152437,
      "title":"Spindrift perfume oil - ozone, musk, water lily, sandalwood, cedar, tansy, oakmoss, labdanum",
      "description":"Spindrift came about because I seem to make a lot of foodie autumn perfumes, and I wanted something different. I love the coast at any time of year, but in the colder months, when the grey waves are crashing on the shore and the salty wind is whipping at my face, I find it truly magnificent. And so, a scent was born.\n\nBase notes of sandalwood, cedarwood, labdanum, and oakmoss create a cool, aquatic body. Notes of musk and blue tansy give Spindrift a misty heart, whilst top notes of water lily and touches of ozone add elegance and sparkle. This is a unisex scent that truly conjures the wilderness of a winter ocean.\n\nLike Spindrift? You might like Wolf Moon too! https:\/\/www.etsy.com\/uk\/listing\/175970521\/wolf-moon-perfume-oil-pine-cedar-violet?ref=sr_gallery_1&ga_search_query=wolf+moon+perfume+oil&ga_order=most_relevant&ga_search_type=all&ga_view_type=gallery\n\nAvailable in a 5ml apothecary bottle or a 10ml roll-on.\n\nAll my perfume oils are made with high quality essential oils, absolutes, and fragrance oils, mixed in skin-loving fractionated coconut oil and vitamin e oil for a silky finish with no grease and great longevity.\n\nPlease remember that some essential oils can cause irritable\/allergic reactions or are unsafe for pregnant women. Always perform a patch test before using a new perfume.",
      "creation_tsz":1455618402,
      "ending_tsz":1466069202,
      "original_creation_tsz":1416750153,
      "last_modified_tsz":1455618402,
      "price":"6.50",
      "currency_code":"GBP",
      "quantity":9,
      "tags":[
        "perfume",
        "perfume oil",
        "fragrance",
        "fragrance oil",
        "unisex perfume",
        "common brimstone",
        "autumn perfume",
        "lily perfume",
        "sandalwood perfume",
        "musk perfume",
        "floral perfume",
        "cedarwood perfume",
        "oakmoss perfume"
      ],
      "category_path":[
        "Bath and Beauty",
        "Fragrance"
      ],
      "category_path_ids":[
        68887336,
        69152437
      ],
      "materials":[
        "sweet almond oil",
        "fragrance oil",
        "essential oil"
      ],
      "shop_section_id":12705582,
      "featured_rank":null,
      "state_tsz":1455568238,
      "url":"https:\/\/www.etsy.com\/listing\/212387093\/spindrift-perfume-oil-ozone-musk-water?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":393,
      "num_favorers":22,
      "shipping_template_id":1091587334,
      "processing_min":5,
      "processing_max":7,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"made_to_order",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":true,
      "taxonomy_id":216,
      "taxonomy_path":[
        "Bath & Beauty",
        "Fragrances"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":221057177,
      "state":"active",
      "user_id":12569503,
      "category_id":69150433,
      "title":"St. Patrick&#39;s Day Bottle Cap Images,Pink and Green 1&quot; Circles.",
      "description":"This listing is for digital bottle cap images.\nYou will receive: \n1 -Non-watermarked\n-high resolution\n-300dpi\n-JPEG file\n\nThe INSTANT DOWNLOAD link will be emailed to the email address on file with Etsy. NO printed materials will be mailed to you. \n\nThe digital file includes a sheet of 15 bottle cap images that are meant to be printed on a 4x6 sheet of photo paper. \n\nColors may vary slightly between online viewing and your actual printed product. Computer monitors display color differently, as well as printers print differently. So please take this into consideration when viewing your design. \n\nThe bottle cap images are slightly bigger than 1 inch so that when you use a 1\u201d hole punch it will not leave a white ring around the image. \n\n-----TERMS OF USE -----\nYou MAY\n- Use my bottle cap images for tangible items to sell i.e- bottle cap jewelry, zipper pulls, key chains, hairbow centers, etc.\n- Make a backup copy on your computer or CD for your own personal use.\n\nYou MAY NOT\n-Resell my images as pre-cut images, iron on transfers, vinyl decals, editable icing images, or scrapbooking kits..\n-The file may NOT be sold, traded or given away digitally. \n\nPlease note, I do not offer a refund or exchanges for digital content. However, I do strive for great customer service. So if you have any issues, please contact me as soon as possible. \n\nBy purchasing this item you are agreeing to the TERMS OF USE listed above. \n\nIf you would like a custom sheet made, please message me.",
      "creation_tsz":1455618400,
      "ending_tsz":1466069200,
      "original_creation_tsz":1422900849,
      "last_modified_tsz":1455618400,
      "price":"1.50",
      "currency_code":"USD",
      "quantity":94,
      "tags":[
        "BCI",
        "St Patricks Day",
        "Bottle Cap Images",
        "1 inch circle images",
        "Bow Centers",
        "BCI Sheet",
        "Pink",
        "Green",
        "Pinch Proof",
        "Daddy's Lucky Charm",
        "Luck O' the Irish"
      ],
      "category_path":[
        "Supplies"
      ],
      "category_path_ids":[
        69150433
      ],
      "materials":[

      ],
      "shop_section_id":17942524,
      "featured_rank":null,
      "state_tsz":1437243035,
      "url":"https:\/\/www.etsy.com\/listing\/221057177\/st-patricks-day-bottle-cap-imagespink?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":415,
      "num_favorers":39,
      "shipping_template_id":null,
      "processing_min":null,
      "processing_max":null,
      "who_made":"i_did",
      "is_supply":"true",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":true,
      "file_data":"1 JPG",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":562,
      "taxonomy_path":[
        "Craft Supplies & Tools"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":268408501,
      "state":"active",
      "user_id":42432876,
      "category_id":69150425,
      "title":"Japanese kokeshi paperdoll magnet 101",
      "description":"This japanese kokeshi paperdoll is totally handmade. \nThe doll is made with traditional japanese washi paper. Its kimono has chrysanthemum flowers on it.\nIt wears a sakura flower in its hair. \n\nThe magnet is hidden inside the doll.\n\nIt&#39;s one-of-a-kind item so don&#39;t miss it !\n\nSize : 10 cm x 8 cm approximatively\n\nFeel free to ask questions.",
      "creation_tsz":1455618399,
      "ending_tsz":1466069199,
      "original_creation_tsz":1455618399,
      "last_modified_tsz":1455618399,
      "price":"5.00",
      "currency_code":"EUR",
      "quantity":1,
      "tags":[
        "japanese",
        "beige",
        "kimono",
        "kawaii",
        "girl",
        "fridge",
        "asian",
        "washi",
        "flower",
        "doll",
        "geisha",
        "obi",
        "brown"
      ],
      "category_path":[
        "Housewares"
      ],
      "category_path_ids":[
        69150425
      ],
      "materials":[
        "paper",
        "strass",
        "magnet"
      ],
      "shop_section_id":null,
      "featured_rank":null,
      "state_tsz":1455618399,
      "url":"https:\/\/www.etsy.com\/listing\/268408501\/japanese-kokeshi-paperdoll-magnet-101?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":0,
      "num_favorers":0,
      "shipping_template_id":null,
      "processing_min":3,
      "processing_max":5,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":[
        "Asian",
        "Kawaii"
      ],
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":1075,
      "taxonomy_path":[
        "Home & Living",
        "Kitchen & Dining",
        "Kitchen D\u00e9cor",
        "Refrigerator Magnets"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":237817298,
      "state":"active",
      "user_id":6520880,
      "category_id":69171721,
      "title":"100 Raw Brass Plain Leverback Earring Findings (15x10 mm) BS-1363",
      "description":"Material : Brass\nSize : 15x10 mm\nQuantity :100 Pcs",
      "creation_tsz":1455618393,
      "ending_tsz":1466069193,
      "original_creation_tsz":1434881018,
      "last_modified_tsz":1455618393,
      "price":"10.00",
      "currency_code":"USD",
      "quantity":583,
      "tags":[
        "brass",
        "findings",
        "metal",
        "tag",
        "finding",
        "blank",
        "raw brass charms",
        "raw brass earring",
        "raw brass",
        "Brass Leverback",
        "Leverback",
        "Leverback Earring",
        "Earring"
      ],
      "category_path":[
        "Supplies",
        "Handmade",
        "Findings"
      ],
      "category_path_ids":[
        69150433,
        69151267,
        69171721
      ],
      "materials":[
        "brass"
      ],
      "shop_section_id":13652680,
      "featured_rank":null,
      "state_tsz":1446195665,
      "url":"https:\/\/www.etsy.com\/listing\/237817298\/100-raw-brass-plain-leverback-earring?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":106,
      "num_favorers":14,
      "shipping_template_id":null,
      "processing_min":null,
      "processing_max":null,
      "who_made":"someone_else",
      "is_supply":"true",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":709,
      "taxonomy_path":[
        "Craft Supplies & Tools",
        "Jewelry & Beading Supplies",
        "Findings & Hardware",
        "Earring Components"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":237792843,
      "state":"active",
      "user_id":10048959,
      "category_id":68887486,
      "title":"Little sun with sunglasses applique sunshine machine embroidery design",
      "description":"This is a digitized machine embroidery design. You need to have an embroidery machine and knows how to transfer to your machine.\n\nThree sizes are included: 3.84&quot;x3.72&quot;, 4.89&quot;x4.74&quot;, 5.71&quot;x5.53&quot;\nThis is an applique design, not a patch.\n\nThe following formats are available:\n\nPES\nHUS\nART\nDST\nEXP\nXXX\nJEF\nVIP\nVP3\n\nDelivery:\nAn instant download link will be available immediately after your checkout.\n\nTerms of Use\nAll my designs are copyright protected and belong solely to Fun Stitch. You may embroider these designs on the items that you sell. However, you may not sell, trade or give away these designs.\nThanks for looking!",
      "creation_tsz":1455618393,
      "ending_tsz":1466069193,
      "original_creation_tsz":1434940375,
      "last_modified_tsz":1455618393,
      "price":"2.89",
      "currency_code":"USD",
      "quantity":95,
      "tags":[

      ],
      "category_path":[
        "Patterns"
      ],
      "category_path_ids":[
        68887486
      ],
      "materials":[

      ],
      "shop_section_id":7229730,
      "featured_rank":null,
      "state_tsz":1434940375,
      "url":"https:\/\/www.etsy.com\/listing\/237792843\/little-sun-with-sunglasses-applique?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":44,
      "num_favorers":11,
      "shipping_template_id":null,
      "processing_min":null,
      "processing_max":null,
      "who_made":"i_did",
      "is_supply":"true",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":"children",
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":true,
      "file_data":"1 ZIP",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":2679,
      "taxonomy_path":[
        "Craft Supplies & Tools",
        "Patterns & Tutorials",
        "Sewing & Needlecraft",
        "Embroidery"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":157758234,
      "state":"active",
      "user_id":10048959,
      "category_id":68887486,
      "title":"Pretty girl owl on a flower tree applique machine emboridery design",
      "description":"This is a digitized machine embroidery design. You need to have an embroidery machine and knows how to transfer to your machine.\n\nThree sizes: 3.91&quot;x3.54&quot;, 4.94&quot;x4.46&quot;, 5.92&quot;x5.35&quot; \n\nThis is a applique design, NOT a patch or iron on.\n\nThe following formats are available:\n\nPES\nHUS\nART\nDST\nEXP\nXXX\nJEF\nVIP\nVP3\nYour design files will be available by instant download immediately after purchase\n\nTerms of Use\nAll my designs are copyright protected and belong solely to Fun Stitch. \nYou may embroider these designs on the items that you sell. However, you may not sell, trade or give away these designs.\nThanks for looking!",
      "creation_tsz":1455618392,
      "ending_tsz":1466069192,
      "original_creation_tsz":1374781651,
      "last_modified_tsz":1455618392,
      "price":"2.89",
      "currency_code":"USD",
      "quantity":980,
      "tags":[

      ],
      "category_path":[
        "Patterns"
      ],
      "category_path_ids":[
        68887486
      ],
      "materials":[

      ],
      "shop_section_id":7229730,
      "featured_rank":17,
      "state_tsz":1455594636,
      "url":"https:\/\/www.etsy.com\/listing\/157758234\/pretty-girl-owl-on-a-flower-tree?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":946,
      "num_favorers":89,
      "shipping_template_id":null,
      "processing_min":null,
      "processing_max":null,
      "who_made":"collective",
      "is_supply":"true",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":true,
      "file_data":"1 ZIP",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":2679,
      "taxonomy_path":[
        "Craft Supplies & Tools",
        "Patterns & Tutorials",
        "Sewing & Needlecraft",
        "Embroidery"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":156626755,
      "state":"active",
      "user_id":10048959,
      "category_id":68887486,
      "title":"Cute baby bumble bee applique machine embroidery design",
      "description":"This is a digitized machine embroidery design. You need to have an embroidery machine and knows how to transfer to your machine.\n\nThree sizes: 3.83&quot;x3.85&quot;, 4.94&quot;x4.96&quot;, 5.92&quot;x5.95&quot; \n\nThis is an applique design, not a patch.\n\nThe following formats are available:\n\nPES\nHUS\nART\nDST\nEXP\nXXX\nJEF\nVIP\nVP3\n\nDelivery:\nAn instant download link will be available immediately after your checkout.\n\nTerms of Use\nAll my designs are copyright protected and belong solely to Fun Stitch. You may embroider these designs on the items that you sell. However, you may not sell, trade or give away these designs.\nThanks for looking!",
      "creation_tsz":1455618390,
      "ending_tsz":1466069190,
      "original_creation_tsz":1373732486,
      "last_modified_tsz":1455618390,
      "price":"2.79",
      "currency_code":"USD",
      "quantity":97,
      "tags":[

      ],
      "category_path":[
        "Patterns"
      ],
      "category_path_ids":[
        68887486
      ],
      "materials":[

      ],
      "shop_section_id":7229730,
      "featured_rank":null,
      "state_tsz":1432169680,
      "url":"https:\/\/www.etsy.com\/listing\/156626755\/cute-baby-bumble-bee-applique-machine?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":95,
      "num_favorers":9,
      "shipping_template_id":null,
      "processing_min":null,
      "processing_max":null,
      "who_made":"collective",
      "is_supply":"true",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":true,
      "file_data":"1 ZIP",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":729,
      "taxonomy_path":[
        "Craft Supplies & Tools",
        "Patterns & Tutorials"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":185949240,
      "state":"active",
      "user_id":6520880,
      "category_id":69150433,
      "title":"100 Raw brass Lobster Claw Clasp  10x5 mm h501 ( A0364 )",
      "description":"Material : Brass\nColor: Raw Brass\nSize :10x5 mm\nQuantity : 100 pcs",
      "creation_tsz":1455618390,
      "ending_tsz":1466069190,
      "original_creation_tsz":1397292889,
      "last_modified_tsz":1455618390,
      "price":"6.50",
      "currency_code":"USD",
      "quantity":2,
      "tags":[
        "lobster clasps",
        "finding",
        "clasp",
        "claw claps",
        "claps",
        "lobster",
        "claw",
        "brass clasp",
        "brass lobster clasp",
        "raw brass clasp",
        "lobster clasp",
        "brass lobster",
        "brass claw clasp"
      ],
      "category_path":[
        "Supplies"
      ],
      "category_path_ids":[
        69150433
      ],
      "materials":[
        "brass"
      ],
      "shop_section_id":13652680,
      "featured_rank":null,
      "state_tsz":1454008461,
      "url":"https:\/\/www.etsy.com\/listing\/185949240\/100-raw-brass-lobster-claw-clasp-10x5-mm?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":1245,
      "num_favorers":108,
      "shipping_template_id":null,
      "processing_min":null,
      "processing_max":null,
      "who_made":"someone_else",
      "is_supply":"true",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":705,
      "taxonomy_path":[
        "Craft Supplies & Tools",
        "Jewelry & Beading Supplies",
        "Findings & Hardware",
        "Clasps"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":233275382,
      "state":"active",
      "user_id":10048959,
      "category_id":68887486,
      "title":"Spring flower pot applique machine embroidery design",
      "description":"This is a digitized machine embroidery design. You need to have an embroidery machine and knows how to transfer to your machine.\n\nThree sizes: 3.65&quot;x3.83&quot;, 4.73&quot;x4.96&quot;, 5.52&quot;x5.79&quot; \n\nThis is a applique design, NOT a patch or iron on.\n\nThe following formats are available:\n\nPES \nHUS\nART\nDST\nEXP\nXXX\nJEF\nVIP\nVP3\n Your designs are for instant download from etsy.\n\nTerms of Use\nAll my designs are copyright protected and belong solely to Fun Stitch. You may embroider these designs on the items that you sell. However, you may not sell, trade or give away these designs.\nThanks for looking!",
      "creation_tsz":1455618390,
      "ending_tsz":1466069190,
      "original_creation_tsz":1431529110,
      "last_modified_tsz":1455618390,
      "price":"2.89",
      "currency_code":"USD",
      "quantity":97,
      "tags":[

      ],
      "category_path":[
        "Patterns"
      ],
      "category_path_ids":[
        68887486
      ],
      "materials":[

      ],
      "shop_section_id":7229730,
      "featured_rank":null,
      "state_tsz":1433178995,
      "url":"https:\/\/www.etsy.com\/listing\/233275382\/spring-flower-pot-applique-machine?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":42,
      "num_favorers":8,
      "shipping_template_id":null,
      "processing_min":null,
      "processing_max":null,
      "who_made":"i_did",
      "is_supply":"true",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":"children",
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":true,
      "file_data":"1 ZIP",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":2679,
      "taxonomy_path":[
        "Craft Supplies & Tools",
        "Patterns & Tutorials",
        "Sewing & Needlecraft",
        "Embroidery"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":246862044,
      "state":"active",
      "user_id":23407780,
      "category_id":69154933,
      "title":"50% OFF Mint and Grey Safari Nursery - Nursery Elephant, Giraffe, LOVE Typography and Dream Big Quote",
      "description":"4 piece mint and grey elephant and giraffe safari nursery print with &quot;Dream Big&quot; quote and &quot;LOVE&quot; INSTANT DOWNLOAD\n\nLooking for a last minute baby shower gift? This is it! Print it, frame it, gift it! Or, spice up your nursery and enjoy these beautiful illustrations created with 100% love.\n\n\u2665 PRODUCT FEATURES:\n- 4 print ready high quality digital files\n- Each file is 8x10 in in size\n- JPG files made for high quality photo print\n- 300 DPI resolution.\n\n\u2665 DELIVERY PROCESS:\nAfter the payment is confirmed, you will receive download link to your email. Please, check your spam folder, as well.\n\nIf you are not able to download your files, please message me and I will send you the files to the email address associated with your Etsy account.\n\n\u2665 YOU WILL DOWNLOAD:\n4 JPG files\n\n\u2665 HOW CAN YOU USE THEM:\nPersonal use only. You CAN&#39;T sell this design in any format. Questions? Contact me.\n\n\u2665 SHOP PROMOTIONS:\nBUY 2 GET 1 FREE - Do not add the free item to the cart - leave your choice of FREE set in the &quot;comments to seller&quot; section and I will email you FREE item. The price of the FREEBIE must be SAME or LOWER than the lowest priced item in your shopping cart.\n\n\u2665 OTHER ELEPHANT OR SAFARI NURSERY SETS:\nhttps:\/\/www.etsy.com\/shop\/igivelove\/search?search_query=elephant+print&order=date_desc&view_type=gallery&ref=shop_search\n\n\nThank you for visiting my shop!\n\nMuch L O V E,\n\u2665 Sandra \u2665",
      "creation_tsz":1455618389,
      "ending_tsz":1466069189,
      "original_creation_tsz":1441419455,
      "last_modified_tsz":1455618389,
      "price":"7.50",
      "currency_code":"USD",
      "quantity":85,
      "tags":[
        "Modern Nursery",
        "Instant Download",
        "Nursery Art",
        "Nursery Illustration",
        "Wall Art",
        "Baby Room",
        "elephant nursery",
        "my sunshine",
        "elephant printable",
        "elephant print",
        "mint green",
        "mint and grey",
        "giraffe mint print"
      ],
      "category_path":[
        "Art",
        "Printmaking"
      ],
      "category_path_ids":[
        68887312,
        69154933
      ],
      "materials":[

      ],
      "shop_section_id":15229071,
      "featured_rank":null,
      "state_tsz":1453380630,
      "url":"https:\/\/www.etsy.com\/listing\/246862044\/50-off-mint-and-grey-safari-nursery?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":145,
      "num_favorers":21,
      "shipping_template_id":null,
      "processing_min":null,
      "processing_max":null,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":"babies",
      "occasion":null,
      "style":[
        "Modern"
      ],
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":true,
      "file_data":"4 JPG",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":119,
      "taxonomy_path":[
        "Art & Collectibles",
        "Prints"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":268511548,
      "state":"active",
      "user_id":8299612,
      "category_id":68887336,
      "title":"Light\/Liner Cloth Pad topped with &#39;&#39;Opalescent Light&#39; minky",
      "description":"Cloth pad light\/liner made from a quality cotton fabric featuring a purple\/teal blue and green squirrels print.\n\nTopped with the same matching cotton print.\nAll light pads have a Hidden PUL layer, one layer of hemp fleece and snap closures (two sockets for width adjustments).\n\nFinished length 21.5 cm or 8.5&quot;.\nApprox weight 21 grams\n\nAll fabrics are pre washed (except for synthetics) to prevent any possible distortions in the finished shape.\n\nHemp fleece is a highly absorbent fabric, perfectly suited as a core material for these cloth pads.\nThe composition of the hemp fleece used here is Hemp 55% Certified Organic Cotton 45% and the thickness is measured as 430gsm.",
      "creation_tsz":1455618388,
      "ending_tsz":1466069188,
      "original_creation_tsz":1455618388,
      "last_modified_tsz":1455618389,
      "price":"9.90",
      "currency_code":"AUD",
      "quantity":1,
      "tags":[
        "cloth pads",
        "reuseable pad",
        "menstrual pads",
        "menstrual cloth pad",
        "minky",
        "Australia",
        "mishmash",
        "mishmash cloth pad",
        "cloth pad",
        "8 inch cloth pad",
        "light cloth pad",
        "cloth pad minky",
        "liner cloth pad"
      ],
      "category_path":[
        "Bath and Beauty"
      ],
      "category_path_ids":[
        68887336
      ],
      "materials":[
        "hemp",
        "PUL",
        "snap fasteners",
        "snaps",
        "cotton",
        "minky",
        "purple",
        "liner",
        "waterproof",
        "light",
        "sea foam",
        "fleece",
        "flannelette"
      ],
      "shop_section_id":17948036,
      "featured_rank":null,
      "state_tsz":1455618388,
      "url":"https:\/\/www.etsy.com\/listing\/268511548\/lightliner-cloth-pad-topped-with?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":0,
      "num_favorers":0,
      "shipping_template_id":null,
      "processing_min":3,
      "processing_max":5,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":"women",
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":274,
      "taxonomy_path":[
        "Bath & Beauty",
        "Personal Care",
        "Menstrual Care"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":193562605,
      "state":"active",
      "user_id":24807747,
      "category_id":68888548,
      "title":"Capricorn Zodiac Sign Carved Crystal Quartz, Garnet, Smoky Quartz, Black Onyx, Brass Accents Bracelet for The Goat, Capricorn",
      "description":"This bracelet features a Capricorn Zodiac sign carved Crystal Quartz, Garnet gemstone rounds, Smokey Quartz and Black Onyx round stone beads. I accented with brass metal spacers. It finishes with a brass lobster clasp and a twisted ring.\n\n\u2606 Healing Properties \u2606\n- Crystal Quartz\nOne of the most powerful healers. Used for meditation, transformation, protection and enlightenment. Promotes general good health and balance.\n\n- Garnet\n Stimulates creativity and passion. Garnet is useful in avoiding bad dreams. Garnets were once exchanged as gifts between friends to demonstrate their affection for one other and to insure meeting again. Helps calm anger. \n\n- Onyx\nProtects against negativity. Balances the physical being and strengthens the mind. It can be used to banish grief, enhance self control, and courage wise decision-making.increases happiness and good fortune.\n\n-Smoky Quartz\nDraws off negative energy. Dissolves negative emotions. Releases fear and depression.\n\n\u2665 Select your preferred size at checkout.\n\n\u2665 To find your comfortable fit, measure your wrist and add \u00bc inches or \u00bd iinches, depending on how snug you like.\n\n\u25ce Important Note for Measurement \u25ce\nMeasurement for sizes of bracelets is inner circumference of bracelet which clasp is closed. It is not measured from end to end including clasp when a bracelet is measured straight. If you&#39;d like me to make one for you by measuring it straight from end to end including clasp, please send me a convo BEFORE purchase!\n\n\u2665You will receive this item gift wrapped.\n\nPlease feel free to contact me if you have any questions. :)\n\nCheck out my other items. http:\/\/jaspersdream.etsy.com\/",
      "creation_tsz":1455618386,
      "ending_tsz":1466069186,
      "original_creation_tsz":1403182700,
      "last_modified_tsz":1455618387,
      "price":"36.69",
      "currency_code":"CAD",
      "quantity":1,
      "tags":[
        "gemstone bracelet",
        "bracelet",
        "bracelet for men",
        "men black bracelet",
        "Garnet",
        "Black Onyx",
        "Capricorn",
        "The Goat",
        "Capricornus",
        "Birthstone bracelet",
        "Smoky quartz",
        "Zodiac jewelry",
        "Crystal quartz"
      ],
      "category_path":[
        "Jewelry",
        "Bracelet"
      ],
      "category_path_ids":[
        68887482,
        68888548
      ],
      "materials":[
        "Metal spacers",
        "nylon coated stainless wire",
        "lobster clasp",
        "metal ring",
        "Garnet",
        "Black onyx",
        "Smoky quartz",
        "crystal quartz"
      ],
      "shop_section_id":13182419,
      "featured_rank":null,
      "state_tsz":1455401654,
      "url":"https:\/\/www.etsy.com\/listing\/193562605\/capricorn-zodiac-sign-carved-crystal?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":358,
      "num_favorers":15,
      "shipping_template_id":5655433499,
      "processing_min":1,
      "processing_max":2,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":"men",
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":true,
      "taxonomy_id":1195,
      "taxonomy_path":[
        "Jewelry",
        "Bracelets",
        "Beaded Bracelets"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":248499507,
      "state":"active",
      "user_id":23889482,
      "category_id":69150467,
      "title":"Sparkle Bow Large Clip *LARGE CLIP ONLY*",
      "description":"your choice of sparkle bow on alligator clip\n*LARGE CLIP ONLY**\nmini clips not available at this time**",
      "creation_tsz":1455618383,
      "ending_tsz":1466069183,
      "original_creation_tsz":1442598938,
      "last_modified_tsz":1455618383,
      "price":"9.00",
      "currency_code":"USD",
      "quantity":17,
      "tags":[
        "sparkle bow",
        "sparkle",
        "bow",
        "shelby",
        "sequin"
      ],
      "category_path":[
        "Accessories"
      ],
      "category_path_ids":[
        69150467
      ],
      "materials":[

      ],
      "shop_section_id":null,
      "featured_rank":null,
      "state_tsz":1455301757,
      "url":"https:\/\/www.etsy.com\/listing\/248499507\/sparkle-bow-large-clip-large-clip-only?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":4655,
      "num_favorers":59,
      "shipping_template_id":9752590446,
      "processing_min":15,
      "processing_max":20,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"made_to_order",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":true,
      "taxonomy_id":1,
      "taxonomy_path":[
        "Accessories"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":268408489,
      "state":"active",
      "user_id":107764,
      "category_id":69151501,
      "title":"Woven Aztec Inspired Studs in Neon Pink, Red and White - Free International Shipping Including the US",
      "description":"These earrings are pretty radical! They use a gorgeously textured, woven textile in red, neon pink and white tones. Aztec inspired and the perfect statement earrings!\n\n*Nickel free clip on backs available for no extra charge - just leave a message at checkout.\n\nThese big, bold button earrings are sure to make a statement. Be prepared for lots of compliments when wearing these! Fabric placement may vary slightly from those pictured.\n\nProduct info: \n\u20222.5cm (1 inch) \n\u2022fabrics are vintage or reclaimed from 101 different sources. \n\u2022buttons are hand pressed using a professional button press. \n\u2022industrial adhesive is used to attach surgical grade stainless steel posts.\n\nPlease note that while I try to be as accurate as possible with color description and photos, colors may vary depending on your monitor.\n\nThank you!",
      "creation_tsz":1455618379,
      "ending_tsz":1466069179,
      "original_creation_tsz":1455618379,
      "last_modified_tsz":1455618534,
      "price":"14.00",
      "currency_code":"AUD",
      "quantity":1,
      "tags":[
        "button",
        "stud",
        "large",
        "fabric",
        "textile",
        "nickel free",
        "bright",
        "woven textile",
        "red and pink",
        "neon pink",
        "aztec jewelry",
        "earrings",
        "button studs"
      ],
      "category_path":[
        "Jewelry",
        "Earrings"
      ],
      "category_path_ids":[
        68887482,
        69151501
      ],
      "materials":[
        "fabric",
        "button shells",
        "surgical stainless steel posts"
      ],
      "shop_section_id":8076888,
      "featured_rank":null,
      "state_tsz":1455618379,
      "url":"https:\/\/www.etsy.com\/listing\/268408489\/woven-aztec-inspired-studs-in-neon-pink?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":0,
      "num_favorers":0,
      "shipping_template_id":1214557869,
      "processing_min":1,
      "processing_max":3,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":"women",
      "occasion":null,
      "style":[
        "High Fashion",
        "Modern"
      ],
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":1203,
      "taxonomy_path":[
        "Jewelry",
        "Earrings"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":236306453,
      "state":"active",
      "user_id":40638966,
      "category_id":69150433,
      "title":"100 Drilled Real Copper green Jewel Beetle wings Elytra Sternocera aequ Taxidermy Fashion Art & Jewellery Earing bracelet craftDesign",
      "description":"The wings size 1&quot; tall and 1\/4&quot; widev approx great for crafting and jewelry making.\nThese wings are &quot;Drilled&quot;\n\nDelivery time 10-20 days depend on Customs proceed and postal dispatch.\nI accept Paypal.\n\nItem can return in 14 days please contact me for instruction and refund.\nThank you.",
      "creation_tsz":1455618376,
      "ending_tsz":1466069176,
      "original_creation_tsz":1433817611,
      "last_modified_tsz":1455618376,
      "price":"19.90",
      "currency_code":"USD",
      "quantity":11,
      "tags":[
        "taxidermy",
        "taxidermied",
        "beetle wing",
        "Jewel",
        "jewelry making",
        "Elytra",
        "Sternocera",
        "insect"
      ],
      "category_path":[
        "Supplies"
      ],
      "category_path_ids":[
        69150433
      ],
      "materials":[
        "beetle wings"
      ],
      "shop_section_id":14710673,
      "featured_rank":null,
      "state_tsz":1450075390,
      "url":"https:\/\/www.etsy.com\/listing\/236306453\/100-drilled-real-copper-green-jewel?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":581,
      "num_favorers":75,
      "shipping_template_id":null,
      "processing_min":1,
      "processing_max":2,
      "who_made":"someone_else",
      "is_supply":"true",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":562,
      "taxonomy_path":[
        "Craft Supplies & Tools"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":248319155,
      "state":"active",
      "user_id":34052305,
      "category_id":68887752,
      "title":"Poppy button set of 6 wooden buttons remembrance day scrapbooking cardmaking sewing crafts baby cardigans hobby creativity poppyfield",
      "description":"These buttons are printed with a field of poppies. \nIdeal for garments, scrapbooking, cardmaking and also for making brooches, necklaces or to put on a hair bow. \n \nThis is a set of 6 buttons.\n\nMeasures are: 3 cm x 3 cm (= that is 1 1\/4&quot; x 1 1\/4&quot; inch)\nWidth: 0.3 cm \n\nPure wood, varnished and washable buttons. \nIdeal for scrapbooking and cardmaking because they are flat buttons to glue on something.\nAlso for baby cardigan and any other garment. \n\nOr to put on a collar for remembrance day.",
      "creation_tsz":1455618375,
      "ending_tsz":1466069175,
      "original_creation_tsz":1442480136,
      "last_modified_tsz":1455618375,
      "price":"2.00",
      "currency_code":"GBP",
      "quantity":4,
      "tags":[
        "buttons",
        "scrapbooking",
        "cardmaking",
        "wooden buttons",
        "buttons for cardigan",
        "cute buttons",
        "card making",
        "hobby",
        "crafts",
        "poppy buttons",
        "poppy field",
        "poppies button",
        "poppies"
      ],
      "category_path":[
        "Supplies",
        "Scrapbooking"
      ],
      "category_path_ids":[
        69150433,
        68887752
      ],
      "materials":[
        "varnished wood",
        "flat buttons",
        "printed with a field of poppies",
        "3 cm diameter"
      ],
      "shop_section_id":14806896,
      "featured_rank":null,
      "state_tsz":1455401450,
      "url":"https:\/\/www.etsy.com\/listing\/248319155\/poppy-button-set-of-6-wooden-buttons?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":103,
      "num_favorers":178,
      "shipping_template_id":null,
      "processing_min":1,
      "processing_max":1,
      "who_made":"someone_else",
      "is_supply":"true",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":731,
      "taxonomy_path":[
        "Craft Supplies & Tools",
        "Scrapbooking Supplies"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":227422451,
      "state":"active",
      "user_id":15320048,
      "category_id":69170993,
      "title":"The Enchanted Forest green gamma printable journal INSTANT DOWNLOAD fairy tale  decoupage paper  Titania and Oberon",
      "description":"Hand in hand, with fairy grace,\t\r\n        Will we sing, and bless this place (Shakespeare)\r\n\r\n\r\nINSTANT DOWNLOAD! \r\nThe file \/ link will automatically be sent to your Etsy email within minutes of purchase\r\nPlease check out this Etsy guide for more information - https:\/\/www.etsy.com\/help\/article\/3949\r\n\r\nThese are digital images which you can download and print yourself.\r\nYou will get\r\n5 pages jpg format + 5 PDF format \u0421MYK mode \r\n10 Background Pages - 5.00&quot; X 7.00&quot; each - Two to a Page\r\nHigh Resolution 300dpi\r\nFits standard 8.5x11 inch size paper when printed.\r\n\r\nTERMS OF USE:\r\n\r\nYou MAY use these images for any craft project you make by hand for personal use or to sell in your own small crafting business, including your Etsy shop.\r\nPurchase doesn&#39;t transfer copyright.\r\nYou may NOT sell or share this digital sheet as is, whether as a digital file or as printed sheets.\r\n\r\nThanks for visiting shop Lala Chandra\r\n\r\nSave money, use these discount coupon codes:\r\n\u00b0 over $10 = 15%: coupon code LALA15\r\n\u00b0 over $18 = 20%: coupon code LALA20\r\n\u00b0 over $25 = 25%: coupon code LALA25\r\n\u00b0 over $50 = 30%: coupon code LALA30\r\n\u00b0 over $100 = 40%: coupon code LALA40\r\n===============================================",
      "creation_tsz":1455618373,
      "ending_tsz":1466069173,
      "original_creation_tsz":1427215216,
      "last_modified_tsz":1455618373,
      "price":"6.00",
      "currency_code":"USD",
      "quantity":96,
      "tags":[
        "Mini Journal",
        "printable journal",
        "decoupage paper",
        "digital paper pack",
        "Enchanted Forest",
        "Fairy background",
        "Titania and Oberon",
        "fairy tales",
        "fairies paper",
        "Fairy Journal",
        "fairy tale journal",
        "blue-green fairy",
        "fairies printable"
      ],
      "category_path":[
        "Paper Goods",
        "Scrapbooking",
        "Journaling Spot"
      ],
      "category_path_ids":[
        69150367,
        68889914,
        69170993
      ],
      "materials":[

      ],
      "shop_section_id":15802119,
      "featured_rank":null,
      "state_tsz":1455611432,
      "url":"https:\/\/www.etsy.com\/listing\/227422451\/the-enchanted-forest-green-gamma?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":170,
      "num_favorers":16,
      "shipping_template_id":null,
      "processing_min":null,
      "processing_max":null,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":null,
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":[
        "\u0412\u0438\u043a\u0442\u043e\u0440\u0438\u0430\u043d\u0441\u043a\u0438\u0439"
      ],
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":true,
      "file_data":"3 ZIP",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":736,
      "taxonomy_path":[
        "Craft Supplies & Tools",
        "Scrapbooking Supplies",
        "Journaling Spots"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":255763912,
      "state":"active",
      "user_id":72427986,
      "category_id":68892008,
      "title":"Dr Seuss Wall Decal Quote Vinyl Sticker Decals Quotes Today You Are You That Is Truer Than True Decal Quote Sayings Wall Decor Nursery ZX242",
      "description":"Dr Seuss Wall Decal Quote Vinyl Sticker Decals Quotes Today You Are You That Is Truer Than True Decal Quote Sayings Wall Decor Nursery Baby \n\nWelcome, You are Incredible! \u10e6\nMy wall decals are more than made with love, they are made with passion!\n\nApproximate Item Sizes:\n\n16&quot; Tall x 23&quot; Wide (inches)\n22&quot; Tall x 32&quot; Wide (inches)\n28&quot; Tall x 41&quot; Wide (inches)\n38&quot; Tall x 55&quot; Wide (inches)\n\n*Picture may not reflect true size. It can be bigger for showing purpose. It helps you to watch all details.\n*Colors may vary slightly depending on your monitor settings\n\nDon&#39;t see the SIZE YOU NEED? \nSend us a message for your custom needs and we will create a listing just for you. \n*The price depends on size of the decal.\n\n\n ABOUT OUR DECALS \n\u221a Our decals are made of Original High Class German Vinyl Material\n\u221a Decals are easy to remove but they are not reusable. \n\u221a They can be applied on any smooth surface like non textured walls, windows, digital gadgets, household appliances and etc. You can apply our decals on cars (hood, window and sides)\n\u221a  Easy to follow application instructions is included\n\u221a You will get a test decal.\n\u221a We accept custom orders. Please contact us with your ideas and we&#39;ll do our best to realize them\n\u221a Fast shipping in safe package tube\n\nRead our policies here:\nhttps:\/\/www.etsy.com\/ru\/shop\/IncredibleDecals\/policy?ref=shopinfo_policies_leftnav\n\nPlease contact me via Etsy with any questions. I am happy to help \u10e6\u10e6\u10e6\nThank you for visiting my store!",
      "creation_tsz":1455618368,
      "ending_tsz":1466069168,
      "original_creation_tsz":1447235098,
      "last_modified_tsz":1455618368,
      "price":"14.99",
      "currency_code":"USD",
      "quantity":97,
      "tags":[
        "wall decal quote",
        "wall decals quotes",
        "quote wall decor",
        "wall decals",
        "nursery wall decals",
        "Vinyl Stickers",
        "dr seuss wall decor",
        "dr seuss wall decal",
        "dr seuss quotes",
        "dr seuss nursery",
        "dr suess decal",
        "Today You Are You",
        "That Is Truer Than"
      ],
      "category_path":[
        "Housewares",
        "Home Decor"
      ],
      "category_path_ids":[
        69150425,
        68892008
      ],
      "materials":[
        "Original German Vinyl"
      ],
      "shop_section_id":17793499,
      "featured_rank":null,
      "state_tsz":1449797598,
      "url":"https:\/\/www.etsy.com\/listing\/255763912\/dr-seuss-wall-decal-quote-vinyl-sticker?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":104,
      "num_favorers":11,
      "shipping_template_id":null,
      "processing_min":1,
      "processing_max":2,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"made_to_order",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":true,
      "taxonomy_id":1028,
      "taxonomy_path":[
        "Home & Living",
        "Home D\u00e9cor",
        "Wall D\u00e9cor",
        "Wall Decals & Murals"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":268511528,
      "state":"active",
      "user_id":37641075,
      "category_id":68888310,
      "title":"Vintage floral English Frenc  fabric piece bundle for projects craft patchwork sewing",
      "description":"10 different vintage and a couple of new fabric piece bundle for small projects, patchwork. craft, appliqu\u00e9 and other similar projects.  Measurements from left to right in inches, 17.5 x 15, 12 x 13, 15 x 12.5, 16 x 13.5, 16.5 x 12.5, 14 x 14, 14.5 x 9.5, 16.5 x 11.5 bottom two, 14 x 11 and 14 x 12.5. All in good clean condition and a mixture of French\/English and new Cath Kidston pieces.\n\nPlease note these are old pieces, some unused, but some may show signs of previous life that I may have missed, but there is nothing obvious I have noticed.  I would say these are all very good pieces.\n\n100% cotton.",
      "creation_tsz":1455618365,
      "ending_tsz":1466069165,
      "original_creation_tsz":1455618365,
      "last_modified_tsz":1455618461,
      "price":"13.85",
      "currency_code":"GBP",
      "quantity":1,
      "tags":[

      ],
      "category_path":[
        "Supplies",
        "Fabric"
      ],
      "category_path_ids":[
        69150433,
        68888310
      ],
      "materials":[

      ],
      "shop_section_id":17974439,
      "featured_rank":null,
      "state_tsz":1455618365,
      "url":"https:\/\/www.etsy.com\/listing\/268511528\/vintage-floral-english-frenc-fabric?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":1,
      "num_favorers":0,
      "shipping_template_id":null,
      "processing_min":1,
      "processing_max":2,
      "who_made":"someone_else",
      "is_supply":"true",
      "when_made":"1960s",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":574,
      "taxonomy_path":[
        "Craft Supplies & Tools",
        "Fabric"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":112663024,
      "state":"active",
      "user_id":21612088,
      "category_id":68925952,
      "title":"And That&#39;s Why You Always Leave a Note \/\/ Arrested Development \/\/ 11 x 17 \/\/ A3 \/\/ RIBBA 290 x 390mm",
      "description":"And thats why\u2026\r\n\r\nThis is an unframed digital print on semi-matte 256gsm heavy weight paper with Ultrachrome K3 ink for a very long lasting life.\r\n\r\nWe are offering 3 different sizing options:\r\n\r\n-- 11 x 17&quot;\r\n-- A3 - 420 x 297mm\r\n-- IKEA RIBBA - 290 x 390mm\r\n\r\n___________________________________________\r\n\r\n\r\nIf you would this print in a different size then you can follow the links below:\r\n\r\nLARGE:\r\n18 x 24&quot; \/\/ A2 - 594 x 420mm \/\/ IKEA RIBBA - 490 x 390mm\r\n\r\nhttps:\/\/www.etsy.com\/listing\/155702944\/large-poster-option-select-from-3-sizes?\r\n\r\nEXTRA LARGE:\r\n24 x 36&quot; \/\/ A1 - 841 x 594 mm \/\/ IKEA RIBBA - 690 x 490mm\r\n\r\nhttps:\/\/www.etsy.com\/listing\/155703200\/xl-poster-option-select-from-3-sizes?\r\n\r\nIf you would like the design in a different size or colourway then please get in touch and we will try our best to accommodate.\r\n\r\nMuch love,\r\n\r\nJoel & Penny\r\n\r\n___________________________________________\r\n\r\n\r\nSHIPPING METHODS & ESTIMATED DELIVERY TIMES\r\n\r\n-- All posters are rolled in kraft paper and shipped in a strong postage tube.\r\n\r\n-- UK \/\/ Royal Mail 1st Class \/\/ 2-3 working days from dispatch\r\n\r\n-- Rest of the World \/\/ Royal Mail Airmail \/\/ 7-10 working days from dispatch\r\n\r\nAll visual media \u00a9 Creative Sobriety Ltd. All Rights Reserved.",
      "creation_tsz":1455618359,
      "ending_tsz":1466069159,
      "original_creation_tsz":1350738559,
      "last_modified_tsz":1455618359,
      "price":"20.00",
      "currency_code":"USD",
      "quantity":5,
      "tags":[
        "Arrested Development",
        "J Walter Weatherman",
        "TV Posters",
        "Graphic Design",
        "Ikea Frame",
        "Home Decor",
        "Typography Poster",
        "The Bluth Family",
        "Blue and White",
        "Leave A Note",
        "Birthday Gift"
      ],
      "category_path":[
        "Art",
        "Print",
        "Digital"
      ],
      "category_path_ids":[
        68887312,
        68892154,
        68925952
      ],
      "materials":[

      ],
      "shop_section_id":12474887,
      "featured_rank":null,
      "state_tsz":1455618357,
      "url":"https:\/\/www.etsy.com\/listing\/112663024\/and-thats-why-you-always-leave-a-note?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":2708,
      "num_favorers":143,
      "shipping_template_id":105684905,
      "processing_min":1,
      "processing_max":3,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":null,
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":true,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":true,
      "suggested_taxonomy_id":119,
      "taxonomy_path":[
        "Art & Collectibles",
        "Prints"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":268511524,
      "state":"active",
      "user_id":29241769,
      "category_id":69150433,
      "title":"Custom Listing for Anne",
      "description":"2x100g 100% Superwash Merino DK\nShades of navy, dark Royal blue and light Royal blue\n\n100g\n225m\n100%Superwash Merino",
      "creation_tsz":1455618351,
      "ending_tsz":1466069151,
      "original_creation_tsz":1455618351,
      "last_modified_tsz":1455618351,
      "price":"25.00",
      "currency_code":"GBP",
      "quantity":1,
      "tags":[

      ],
      "category_path":[
        "Supplies"
      ],
      "category_path_ids":[
        69150433
      ],
      "materials":[

      ],
      "shop_section_id":18258091,
      "featured_rank":null,
      "state_tsz":1455618351,
      "url":"https:\/\/www.etsy.com\/listing\/268511524\/custom-listing-for-anne?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":0,
      "num_favorers":0,
      "shipping_template_id":15974145043,
      "processing_min":null,
      "processing_max":null,
      "who_made":"i_did",
      "is_supply":"true",
      "when_made":"made_to_order",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":null,
      "is_private":false,
      "recipient":null,
      "occasion":null,
      "style":null,
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":false,
      "taxonomy_id":2437,
      "taxonomy_path":[
        "Craft Supplies & Tools",
        "Fiber & Textile Art Supplies",
        "Yarn & Roving",
        "Yarn",
        "DK"
      ],
      "used_manufacturer":false
    },
    {
      "listing_id":268408459,
      "state":"active",
      "user_id":33758198,
      "category_id":68933546,
      "title":"White shirt, kurta style, blue indigo collar, babys, boys",
      "description":"White long shirt, with printed blue collar and button placket, for boys and babys.\nCambric\n100% cotton\n\nMachine washable.\n\nThis shirt makes a set with the Alibaba royal blue pants.",
      "creation_tsz":1455618338,
      "ending_tsz":1466069138,
      "original_creation_tsz":1455618338,
      "last_modified_tsz":1455618451,
      "price":"21.00",
      "currency_code":"EUR",
      "quantity":1,
      "tags":[
        "summer",
        "designer",
        "comfortable",
        "boys",
        "shirt",
        "white",
        "blue",
        "mao collar",
        "kurta",
        "india",
        "indigo",
        "baby's shirt",
        "boy's top"
      ],
      "category_path":[
        "Clothing",
        "Children",
        "Baby"
      ],
      "category_path_ids":[
        69150353,
        68889526,
        68933546
      ],
      "materials":[
        "coton",
        "cambric"
      ],
      "shop_section_id":13663442,
      "featured_rank":null,
      "state_tsz":1455618338,
      "url":"https:\/\/www.etsy.com\/listing\/268408459\/white-shirt-kurta-style-blue-indigo?utm_source=workingonit&utm_medium=api&utm_campaign=api",
      "views":0,
      "num_favorers":0,
      "shipping_template_id":643877043,
      "processing_min":1,
      "processing_max":3,
      "who_made":"i_did",
      "is_supply":"false",
      "when_made":"2010_2016",
      "item_weight":null,
      "item_weight_units":null,
      "item_length":null,
      "item_width":null,
      "item_height":null,
      "item_dimensions_unit":"in",
      "is_private":false,
      "recipient":"children",
      "occasion":"anniversary",
      "style":[
        "Zen",
        "Traditional"
      ],
      "non_taxable":false,
      "is_customizable":false,
      "is_digital":false,
      "file_data":"",
      "language":"en-US",
      "has_variations":true,
      "taxonomy_id":377,
      "taxonomy_path":[
        "Clothing",
        "Boys' Clothing",
        "Baby Boys' Clothing"
      ],
      "used_manufacturer":false
    }
  ],
  "params":{
    "limit":25,
    "offset":0,
    "page":null,
    "keywords":null,
    "sort_on":"created",
    "sort_order":"down",
    "min_price":null,
    "max_price":null,
    "color":null,
    "color_accuracy":0,
    "tags":null,
    "category":null,
    "location":null,
    "lat":null,
    "lon":null,
    "region":null,
    "geo_level":"city",
    "accepts_gift_cards":"false",
    "translate_keywords":"false",
    "etsy_asap":"false"
  },
  "type":"Listing",
  "pagination":{
    "effective_limit":25,
    "effective_offset":0,
    "next_offset":25,
    "effective_page":1,
    "next_page":2
  }
}
